# .gitlab-ci.yml

# The Docker image that will be used to build your app
image: node:20.9.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

variables:
  CI: "false"

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  needs: [build]
  script:
    - cp -r build/* public
  artifacts:
    paths:
      - public
